dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
env:
  - PYTORCH_VERSION=1.1.0
install:
  - pip install "torch==$PYTORCH_VERSION" sklearn
  - pip install pytest pytest-cov codecov
  - pip install flake8 flake8-bugbear black pydocstyle isort
script:
  - black chatspace --check
  - flake8 chatspace
  - isort -rc -c .
  - python -m pytest
after_success:
  - codecov
